### PR TITLE
Handle East Asian wide characters

### PR DESCRIPTION
**Pull request by roy2220**
Nice work!

I noticed the line length calculation is inaccurate since the width of some east Asian characters could be 2.

### CODE REVIEW

**Comment by ymattw** [comment]
Thank you.  I'd like to keep support python 2.7 for a while, would you mind fix the backward compatibility issue? The test result above has the detail.

Also, I'd appreciated if you could add a test case. Instructions are in tests/README. Thanks!

**Comment by roy2220** [comment]
Okay, it will take me some time to finish it

**Comment by ymattw** [comment]
Would you mind squash all commits into one, so that we do not leave commits that fail tests in the history?

**Comment by roy2220** [comment]
@ymattw Feel free to squash commits / change commit messages :)

**Comment by krader1961** [comment]
@roy2220: FWIW, the project owner can certainly squash your commits. However, if they prefer the person submitting the changes do so that is not an unreasonable request. I'm a grey-beard who has contributed to lots of changes to various projects, both open and closed source, over my four decades as a software engineer. I've found it is usually a good idea to adhere to a project's norms if they are reasonable. And if they aren't either try to change those norms or give up on the project. 😄 It is trivial for you to "git rebase -i" to squash your commits and do a "git -f push" so I'm perplexed why you didn't simply do so.

**Comment by roy2220** [comment]
@krader1961 Thank you, maybe I misunderstood (there is a `Squash` option on the pull request), now I have done it manually.

**Comment by ymattw** [comment]
The PR needed a rebase but I manually merged from command line, thank you!

I did not know the "Squash" option on the web UI, I still prefer doing this from command line though, because that way I can see what happens before git push.  In your case it would require fetching latest changes from master first, then git rebase -i upstream/master and squash, here is a [guide](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) if you are interested to learn.

Thank you again for the contribution!

**Pull request closed without merging**
