### PR TITLE
Support for bypassing paging - #82

### PR DESCRIPTION
**Pull request by tomcruise81**
* This aims to implement a solution for #82. The idea is that paging can be bypassed. The purpose is to be able to still output colorized and side-by-side output through an ANSI processor to ensure ANSI escape sequences are handled properly.
* Removed outdated Python versions, and added newer ones from/to .travis.yml

### CODE REVIEW

**Comment by ymattw** [comment]
Thanks for the pull request.  I am not sure forcing users to use `cat` as an alternative pager is a good idea.  How about having two options:

* --pager, default to `less`, this way we do not force users to use `cat` as an alternative pager
* --pager-options, default to `''`, because `cat` can also take useful options.

And ['-FRSX', '--shift 1'] will be set only when --pager is NOT explicitly set (and pager default to less).

**Comment by tomcruise81** [comment]
Sounds good to me. Is that something you wanted to implement?

**Comment by ymattw** [comment]
Hi @tomcruise81, you are welcome to continue the effort since you started.

**Comment by ymattw** [comment]
Thanks for your PR, would you do a rebase and squash the commits into one, please?  The diff is kinda hard to read now.

**Comment by tomcruise81** [comment]
Can't seem to get git to work for me today. I'll just re-create the PR rebased off of your latest work.

**Pull request closed without merging**
